### ISSUE TITLE
Clean twitter tracker links

### ISSUE THREAD

**Issue by shamilsherhan** [TrianguloY/UrlChecker#121]
**Need to redirect to actual urls from t.co links used by twitter**
Twitter uses t.co urls to wrap links shared through twitter. 

UrlChecker needs to identify this and provide the actual link, maybe by doing background redirect.

**Sample link**
[https://t.co/GMECRfdWf7](https://t.co/GMECRfdWf7) redirects to [https://antennapod.org/blog/2022/10/2-7-release](https://antennapod.org/blog/2022/10/2-7-release)

**Comment by shamilsherhan** [comment]
Ok. I was looking into the cleaner module.

**Comment by TrianguloY** [comment]
The cleaner module does offline redirections, when the url contains all the information, no need for any external petition. That's why that's automatic.

Twitter links are basically url shorteners, the real url is only available in twitter servers, you need to "Check the status" to obtain the redirection.
