### ISSUE TITLE
Clean affiliate links

### ISSUE THREAD

**Issue by aamarioneta** [TrianguloY/UrlChecker#151]
Possibility to remove the affiliate from links e.g. affiliate link
https://www.awin1.com/awclick.php?mid=19812&id=269979&clickref=18003b7jjln&ued=https%3A%2F%2Fwww.sharkclean.de%2Fprodukte%2Fshark-akku-staubsauger-iz103eugb-40-minuten-laufzeit-selbstreinigende-buerstenrolle-zidIZ103EUGB

to this:
https://www.sharkclean.de/produkte/shark-akku-staubsauger-iz103eugb-40-minuten-laufzeit-selbstreinigende-buerstenrolle-zidIZ103EUGB

or even a custom RegEx filter.

https://urlclean.com/ does this.

**Comment by TrianguloY** [comment]
This is a task for the Url Cleaner module.
It seems the official rules don't have this domain (awin1) yet. There is [an issue for it](https://github.com/ClearURLs/Rules/issues/49). You can either wait until they create it and then update the database, or create the entry manually by [following the specifications](https://docs.clearurls.xyz/1.23.0/specs/rules/).

You can also use the Patterns checker module for [simpler regexp modifications](https://github.com/TrianguloY/UrlChecker/wiki/Custom-patterns).

I'll close this issue since I think the current modules can perform the already wanted feature. Fell free to reopen if you disagree.
