### ISSUE TITLE
Option to hide modules while keeping them enabled

### ISSUE THREAD

**Issue by PabloOQ** [TrianguloY/UrlChecker#224]
### Describe a related problem (optional)

I usually do not use the "Status code" module but I like to keep it enabled for the times I need it. I feel the same with some other modules too, so I might have 3 modules that I rarely use, but that are very useful when I need them. When those are not needed the URLCheck dialog is unnecessarily big and cluttered.

### Describe your suggested feature

A way to hide these modules in an overflow menu like the one in the "Queries remover" or "Flags editor". Maybe even have the visibility be decided by a regex matching the URL.

### Describe alternatives you've considered for your suggested feature

Disabling the modules.
Moving these under the "Open with" module, so I know that everything that is always relevant is in the upper half of the dialog, and circumstantial modules are in the lower half.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
In the newer update (as you probably saw) modules will be hidden when you can't interact with them and they don't have any information to show.

Collapsing them to a dropdown each is probably counterproductive, since all modules that 'are just there' are very small (if there is one that isn't we can try to reduce that one).

Maybe a global dropdown to collapse all there?

Or wait, what about a 'separator' so that all modules under it will be hidden by default in the separator toggle? This is probably very easy to implement, it will be just a normal module with a special feature for the window, and it will also be easy to setup (just move them below, as you describe!)

**Comment by PabloOQ** [comment]
> Maybe a global dropdown to collapse all there?

Certainly! That was what I meant.

> Or wait, what about a 'separator' so that all modules under it will be hidden by default in the separator toggle? This is probably very easy to implement, it will be just a normal module with a special feature for the window, and it will also be easy to setup (just move them below, as you describe!)

I was thinking about this too, but it didn't feel right to me. However, you are right, that is probably the easiest option and seeing that we can't implement much of the proposed features because lack of time, maybe that's the best way.

**Comment by TrianguloY** [comment]
```java
t=new Intent(Intent.ACTION_VIEW,Uri.parse("http://google.es"))
t.putExtra("private_browsing_mode",true)

cntx.startActivity(t)```

It works! I'm using the latest play store Firefox version, and I can confirm that the code above works! (even if UrlChecker is opened and then you choose Firefox, thanks past me for keeping the original intent)

Thank you for the discovery and the links! I remember seeing that class, but probably didn't invest much time searching.

Reopening to implement!
It will only work for Firefox, but it will be really useful for me so...
