### ISSUE TITLE
URL Status check broken for some urls since version v2.10

### ISSUE THREAD

**Issue by sokripon** [TrianguloY/UrlChecker#225]
### Steps to reproduce

url: https://www.embedreddit.com/r/test/comments/agi5zf/test/
Click the Check label/button

### Expected behavior

In version 2.9.1 the check returned a redirect
![image](https://github.com/TrianguloY/UrlChecker/assets/79755465/8df73bf4-f8c8-4e62-ad57-9adcacfaff2b)

### Actual behavior

In version 2.10 and above the check returns a 404
![scrcpy_ZWbcz0X6FZ](https://github.com/TrianguloY/UrlChecker/assets/79755465/ccd9afcb-691c-46a8-bfbc-b95aad380905)

### URLCheck version

2.10

### Android version

Android 12

### Android Custom/Specific ROM or Device

MIUI

### Other details
This occurs because some websites don't implement HEAD requests properly.
A suggestion for a fix would be to first try a HEAD request and if that fails a GET request.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Nice and clear report, thanks!

As suspected, the bug occurs because that server isn't following the HEAD convention, which should be the same as GET but without returning any content (so, theoretically, faster). I changed from GET to HEAD in v2.10.

I can revert back to GET, which should fix this issue, but may be slower. I'll try to either add a setting to choose which one to use, or somehow make one or the other automatically (maybe both?).

**Comment by TrianguloY** [comment]
Edit: I somehow missed your other details part, sorry. You were on point.

But, after searching for similar questions, I found that HEAD is not a replacement in a general case. Some sites will return 404, others 500, and others even 200 (always) to combat bots.

I'll revert to using GET, it's the safest and best approach. I may add a setting to use HEAD instead, but I doubt it. If #33 is implemented it will most probably allow it.
