### ISSUE TITLE
Unshorten url error and a suggestion

### ISSUE THREAD

**Issue by hidp123** [TrianguloY/UrlChecker#226]
### Steps to reproduce

Try sharing the following link and click unshorten:
https://maps.app.goo.gl/ooruyKF1mLwK1ZENA

I get the following error:
![Screenshot_20230512-222135](https://github.com/TrianguloY/UrlChecker/assets/84683703/b5c32c52-61ca-4dc1-af6d-d186298c277a)

The following android app works perfectly with this link, and what's more, it's open source, does not require an Internet connection and is in java!

https://play.google.com/store/apps/details?id=com.redinput.share2browser
https://github.com/kix2902/url-extractor-and-expander

### Expected behavior

The link should be expanded as follows:
https://www.google.com/maps/place/Riverside+Building,+London+Eye+River+Cruise,+County+Hall,+Westminster+Bridge+Rd,+London+SE1+7PB/data=!4m2!3m1!1s0x487604c7b764c501:0x61a09eaf07649a32?utm_source=mstt_1&entry=gps&g_ep=CAESCTExLjc3LjMwMBgAIIgnKgBCAkdC&ucbcb=1 .

### Actual behavior

Error. See screenshot attached.

### URLCheck version

2.10

### Android version

Android 9

### Android Custom/Specific ROM or Device

Oneplus 3 stock

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
The issue is that your url has a title above, so it isn't a valid url (everything in the edit box is considered part of the url). You need to remove the title and keep only the https... part.

In any case, for errors like this the module isn't reporting the error correctly, I'll consider that bug and fix it.

**Comment by hidp123** [comment]
Thanks. Can you make it such that it automatically detects the url as well, like the other app I linked to does. Thanks

**Comment by TrianguloY** [comment]
Detecting urls on text is not an easy task, but I'll think about it (maybe just split by line breaks...)

**Comment by hidp123** [comment]
Ok.
https://github.com/kix2902/url-extractor-and-expander
Can this code be incorporated, if licensing allows, and if it's easier than writing your own code/parser?

**Comment by TrianguloY** [comment]
> Ok.
> https://github.com/kix2902/url-extractor-and-expander
> Can this code be incorporated, it's open source, if licensing allows, and if it's easier than writing your own code/parser? 

I don't see anything special in that code. It is detecting the urls with a custom (and complex) regexp, expanding google redirections and performing network connections to check redirections.

There is a better official regexp for getting urls, I can try to add that.
The other two features are already available.

**Comment by hidp123** [comment]
One advantage I found was that it did not have the 10 requests per hour limit that we have.

**Comment by TrianguloY** [comment]
The unshorter module has a limit because it uses an external service to check redirections. Your device isn't checking the page, theirs is, so it may be a bit more secure if you want to avoid petitions from your ip (and you trust that other service). The link you provided does not have this integration.

The status module is the one checking the petition from your device, so it doesn't have any limit but malicious servers may log your ip. This is what the link you provided does.

And the clearUrl module makes redirections offline (no network petition required) but of course this only works if the url already has the final url encoded, which isn't the case for shortening services. The link you provided has the google redirection only (and hardcoded)

**Comment by whyjxz14** [comment]
@TrianguloY Unshorten.me could not resolve https://t.co/ url recently, reporting “Unknown Error!”

**Comment by TrianguloY** [comment]
Unfortunately unshorten.me is the one reporting the error (you can check by entering the url in their [main page](https://unshorten.me/).
I wasn't able to find any report about it, but there is nothing I can do (other than include a custom error, but maybe they fix it next week, who knows)
