### ISSUE TITLE
URLCheck doesn't open when launched from Samsung widget popup panel

### ISSUE THREAD

**Issue by pressRtowin** [TrianguloY/UrlChecker#228]
### Steps to reproduce

1. Install One Handed Operation + on any Samsung device with Good Lock support and enable a gesture for the widget popup panel. 
2. Add URLCheck to the panel. 
3. Copy a URL and tap on it. 
4. It doesn't open. 

### Expected behavior

URLCheck should appear

### Actual behavior

It does not. 

### URLCheck version

2.11

### Android version

13

### Android Custom/Specific ROM or Device

One UI 5.1

### Other details

This may be hard to debug. Not sure what's going on here. The shortcut works fine from the launcher but not from the popup panel. Maybe because the popup panel itself is an app (Tasker's AutoInput detects it as com.samsung.android.sidegesturepad)? But other tools like Universal Copy launch fine from the panel. Lmk if there's anything I can do to help figure this out. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Hard to debug, yes. Thanks for offering to help, but I have no idea what to ask! Maybe check the logcat? compare the manifest with other working apps?

I think a relative has a Samsung phone, I'll try to test on his device.

Just to be sure, the shortcut you set in the side panel is just the 'open link from clipboard' shortcut right?

**Comment by TrianguloY** [comment]
> > Hard to debug, yes. Thanks for offering to help, but I have no idea what to ask! Maybe check the logcat?
> 
> Any idea what to look for?

As soon as you press the icon you should probably see a line from the side panel app (maybe not) and then some lines from url checker (I think it prints a few debug things...). Any other "error can't launch" or red things may help too.

Since pressing the icon is instant, you should be able to check the few lines at that moment...and hope to see anything relevant 👀

**Comment by TrianguloY** [comment]
Nono, don't worry, the previous screenshot was perfect. I tested and notice that I didn't programmed correctly the shortcut feature (the old one).

I made a testing fix [here](https://github.com/TrianguloY/UrlChecker/pull/229), in a few minutes an automatic apk will appear (subscribe to that pr for a notification), if you are able to test it and confirm if it is fixed that would be perfect!

**Comment by TrianguloY** [comment]
Btw: the key part was the `Intent does not match component's intent filter: Intent { act=android.intent.action.VIEW flg=0x10000000 cmp=com.trianguloy.urlchecker/.activities.ShortcutsActivity }`

You can see that the intent has a VIEW action (act) but the manifest of the app does not.
I just [added it](https://github.com/TrianguloY/UrlChecker/pull/229/commits/0e849d59dcb1c5888959eb1450c1946779b2513a#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cd).

**Comment by TrianguloY** [comment]
> Odd that it worked from the home screen but not the widget panel . . . 


Indeed. The home screen uses the new android shortcuts, which for some reason seem to bypass the intent filters, no idea why.

> I just tested the fix and it launches now!

Wonderful! Thank you for the check. I'll merge it now.

> Off topic but I noticed you changed the way the popup scales on displays in the new version. While overall it does feel more in place on a larger device now, some modules start to suffer from uh . . . "Too Wide Syndrome"? If you've ever played a game that wasn't optimized for ultrawide displays on an ultrawide or surround/eyefinity setup and opened the game settings you'll know whatI'm talking about. 

That sure is a wide screen! 

There are no changes in this version compared to v2.11 in the way the layout is defined. To be honest the size of things is just as Android wants (it's easier that way). The only difference is the incognito button. What happens if you hide it? (From the open module settings, set it to always on or always off). 

I'll check the layout again just in case, but maybe I should add a maximum width? Hmm.
Can you create a new issue for this? It will be easier to manage.
