### ISSUE TITLE
Some URLPATTERNS not recognized after update

### ISSUE THREAD

**Issue by tEctutoRIt** [TrianguloY/UrlChecker#245]
### Steps to reproduce

1. Launch the URLChecker app.
2. Enter the URL: https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox.
3. Observe that no options are displayed for applying the pattern.

### Expected behavior

The URLChecker app should display an option to apply the pattern defined in the Urlpatterns JSON file.

### Actual behavior

The specific pattern I am encountering the issue with is as follows:
Pattern Name: Play Store ➔ Apkmirror
Regex: "^https?:\/\/play.google.com\/store\/apps\/details?id=(.*)",
Replacement: "https:\/\/www.apkmirror.com\/?s=$1",
Enabled: true

But its not the only one, many other patterns are not shown as an option

### URLCheck version

2.11

### Android version

Android 13

### Android Custom/Specific ROM or Device

One UI

### Other details

No recent changes have been made to the app, except for a recent update. After which this issue started 
Here is a link to my complete patternchecker-config.json: 
[patternchecker-config.json](https://0.0g.gg/?cd5cee76079f562e#DdiWZ3oAYPdXZLybwjy3i5yxLAMMocW7F7Z5ur8YRThZ) 
Please let me know if any further information is required to resolve this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tEctutoRIt** [comment]
I didn't even notice it all the time. I was a bit naive, thank you for helping me.

**Comment by TrianguloY** [comment]
Happy to hear the issue was resolved, tanks Murilogs for you help! 

By the way, that patterns config collection is quite impressive, have you considered sharing some of them on the [wiki](https://github.com/TrianguloY/UrlChecker/wiki/Custom-patterns)?

I also see that you have some automatic patterns to fix the encoded urls. I think that using the ClearUrl catalog (where you can include you own patterns too) may be more powerful, although the syntax is different.

Still, that gave me an idea, what about a new entry "decode" as boolean (false by default) that will automatically decode the whole string after replacing? Could that be useful?

**Comment by TrianguloY** [comment]
> Oh, there is a wiki! Octodroid doesn't support that, so I didn't know.

Not sure if it can be called a wiki (it's write empty) but yes, it's a list.

> Wouldn't your patterns be cleared when you update the ClearURL catalog tho?

You can write them on a separate parent object, only the "providers" one is replaced.

> Also, how would it be more powerful?

It's specifically designed to manage url queries. Maybe "powerful" is not the correct word, "precise" maybe.

> You mean as a new module/option in a module? I guess that'd be useful, yeah.

No, I meant in the current patterns module. A new entry (regex, replacement, decode...).

**Comment by TrianguloY** [comment]
Apparently you can use embedded flags: https://stackoverflow.com/a/43699249

A pattern like "(?i)you" will match you, YOU, YoU, etc.
