### ISSUE TITLE
Port UrlChecker to PC

### ISSUE THREAD

**Issue by gitthepie** [TrianguloY/UrlChecker#259]
### Describe a related problem (optional)

No, the lack of a PC port is not a problem with the mobile app per se.

### Describe your suggested feature

I've found UrlChecker to be an extremely useful app. Unfortunately, I can only use it on mobile devices. If UrlChecker could be ported to PC, I'd be able to get much more work done.

### Describe alternatives you've considered for your suggested feature

Short of somehow running a mobile app on a PC, there is no alternative.

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
A pc port will need to be developed from scratch, and I don't have enough experience on pc apps.
But I guess the browser is the place for something like that, maybe a custom plugin or so...which I also lack experience :(

In any case I think most of the features are already available as browse plugins, although maybe not all together.

So, I'm sorry but I'll close this issue since I struggle a bit to keep the app updated, and to think about a totally different one...

But hey, if someone else wants to do it I'll be glad to link it! (especially if they mention this as inspiration or baseline) 😊

**Comment by TrianguloY** [comment]
Some alternatives: https://github.com/TrianguloY/UrlChecker/discussions/223
