### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Martinligabue** [TrianguloY/UrlChecker#261]
### Describe a related problem (optional)

I do not understand what the icon in the bottom left of the app while opening urls does

### Describe your suggested feature

I'd make a wiki or at least some documentation to thoroughly detail the features of the apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
I guess you mean the custom tabs button (or maybe the Firefox private mode?).

You can long tap to see a description.
And the open module description (from the modules list) explains all of them.

I guess a wiki could be useful, at least for less common features, but personally I prefer to have everything in the app itself since it's easier to update and less probable to forget about it.

But, even in that case, the wiki here on Github is a good place for user-generated help, I think anyone can suggest new or edit pages (if not just say so!).

Discussions are also another good place for more common help, in fact your question alone would have fit better there.

I'll close this issue because I don't plan to create a full wiki myself, but as I said anyone is encouraged to suggest wiki changes or help with discussions.
