### ISSUE TITLE
Some url request(or activity?) doesn't prompt anything while UrlChecker set as default browser

### ISSUE THREAD

**Issue by NotExist** [TrianguloY/UrlChecker#278]
### Steps to reproduce

I ran into the issue while I'm trying login [Bitwarden](https://play.google.com/store/apps/details?id=com.x8bit.bitwarden).
And it works in most other cases(links) at same time.

0. Configure UrlChecker as default browser
1. Install Bitwarden (GooglePlay/f-droid version doesn't matter)
2. Login with credential
3. Popup keeps loading, sometime it will abort with software message.

### Expected behavior

UrlChecker will popup and decide how to open the hCaptcha interface.

### Actual behavior

Nothing happen, not even a single message.

### URLCheck version

V2.12

### Android version

12

### Android Custom/Specific ROM or Device

Stock

### Other details

If I set Chrome as default browser, a custome tab (the same frameless simple browser which "custome tab" feature will bring) will show up and provide a hCaptcha interface to interact with. But nothing will happen while UrlChecker is configured as default browser.

Please ensure the system will fall into the condition that require hCaptcha while login, I believe https://vault.bitwarden.com will provide similiar check mechanism.

And, if there's any information or debug procedure I can cooperate with, I'm glad to help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Seems to be something related to the custom tabs service. With this service apps can requests browsers to open a connection in the background, ideally to pre-load the page before the user loads it (the example google uses is to pre-load a link in gmail so that it is immediately opened when you click it).

In order to intercept links opened as custom tabs, the app is registered as a valid custom tabs browser. But, since the app itself isn't a browser, it simply [rejects this pre-caching](https://github.com/TrianguloY/UrlChecker/blob/290a1e06331d55cf25c27726039e75cee3ddc9fa/app/src/main/java/com/trianguloy/urlchecker/services/CustomTabs.java#L44). Apparently Bitwarden isn't detecting the invalid service, and it hangs.

Not sure where is the issue. If I try to mock the service, other apps may start failing. So far this is the only app I'm aware to have this issue (doesn't mean there are more, though).
Have you tried contacting Bitwarden just in case? 

I'm afraid I don't know how to solve it without removing the full custom tabs service (which will stop the app for intercepting those links), sorry.

**Comment by NotExist** [comment]
Haven't contacted Bitwarden yet, since I have no technical information to discuss with them, but thanks for your additional information, I'll try to figure out how can I work on this, thanks!
