### ISSUE TITLE
Bad cleaning on ClearURLs module

### ISSUE THREAD

**Issue by PabloOQ** [TrianguloY/UrlChecker#28]
When using the ClearURLs module, this URL `https://www.google.com/amp/s/github.com` gives different results on the official addon.
On the addon: `http://github.com`
On UrlChecker: `github.com`
After this, UrlChecker can't find an app to open the link with, resulting in "NO APPS" in the Open & Share module.

Version 2.3

**Comment by TrianguloY** [comment]
I think the clearurl is applied correctly, the original google link doesn't have the http part so the replacement rule is applied correctly.

The main issue is that "github.com" is not detected as an url by android, that's why it says "no apps". A solution would be to automatically add an http:// is it's not found, either globally or in the clearurl module process only. Another solution is to add a new rule to the patterns checker, that will include a link to add it.

The patterns checker module is expected to be able to automatically apply the patterns, which will solve this issue. In the meantime it can be temporarily added to the clearurl or globally.

**Comment by PabloOQ** [comment]
I understand, then I think ClearURL should add it, as the cleaning tool of the addon does, but patterns checker should look for it too.
