### ISSUE TITLE
previously used browser dissapears from list temporarily for few seconds

### ISSUE THREAD

**Issue by pokegamer5547** [TrianguloY/UrlChecker#305]
### Steps to reproduce

1. Open any url via urlcheck
2. Click custom tabs button and open via any browser
3. Click close button in the browser
4. Reopen the url via urlcheck

### Expected behavior

All browsers should still be on list.

### Actual behavior

The browser which you previously used custom tabs feature with dissapears from list temporarily. 

### URLCheck version

2.13.1

### Android version

android 13

### Android Custom/Specific ROM or Device

lineage os 20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Are you sure your test is correct? Can you confirm:

1- In step 4, are you using the same browser as the one in step 2? (So, if you are opening the link in chrome+custom tabs, are you trying to open a link from chrome?)
2- Does it also happens if you don't use custom tabs? (just repeat the same steps, but don't click the custom tabs icon).
3- What happens if, after opening the link in step 4 (where the browser is not found) you want 5 seconds and then change something (for example you edit the url then revert) is it readded?
4- Do yo have the 'hide the source app (referrer)' setting in the open&share module settings enabled?

There are only two features that can 'remove' elements from the list: one is the referrer (disabled by default) the other is the new 'rejector detector' that will hide any app where a specific url was opened less than 5 seconds ago: sometimes you open an url in, for example, the github app. But the app cannot open the link and reopens it again. In this case the app detects that the link that was 'sent' to github is reopened quickly by github, so it hides github assuming the app cannot open that link.

**Comment by TrianguloY** [comment]
Hmm, in your video, which app are you using for those notes? (The app that says "note to self")

**Comment by pokegamer5547** [comment]
> Hmm, in your video, which app are you using for those notes? (The app that says "note to self")

Signal app but same can be reproduced using the "source code" button in the urlcheck app.

**Comment by TrianguloY** [comment]
Hmm, so it is a different app. That does seem like a bug, I'll investigate.
Thanks for the report!
