### ISSUE TITLE
Sharing causes browser to act weirdly

### ISSUE THREAD

**Issue by HarriBuh** [TrianguloY/UrlChecker#314]
### Steps to reproduce

1. Share URL link to URLChecker to purge it from trackers etc.
2. Use URLChecker to send clean link to browser
3. Wonder why browser stops loading page
4. Wonder why browser opens link in minimized tab and stops loading it further

### Expected behavior

The app should act as expected: Open the clean link in any browser without any further issues.

### Actual behavior

See reproduction.

### URLCheck version

2.13.1

### Android version

14

### Android Custom/Specific ROM or Device

Google Pixel 7

### Other details

Note: URLCheck will still work flawlessly in 7/10 cases.

I tested it with three different browsers (Cromite, Brave, FREE Browser).

Over I deactivated URLCheck and tried sharing links directly to the browsers, the issue disappeared.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PabloOQ** [comment]
I'm not familiar with the current version (code wise) of the Open Module, so I'm not sure if I can help, but these questions could lead to the issue.

1. Did this happen in previous versions? If you are not sure, how long has this been a problem for you? There are some changes in the Open Module between 2.13.1 and 2.13.0, so that might be why.
2. Do you get any toast message?
3. What is your config of the Open Module?
4. What modules do you have enabled?
5. Just to clarify, does this happen if you open the URL with the URLCheck instead of opening it with URLCheck? 

Thank you.

**Comment by PabloOQ** [comment]
> 3. Don't know what you mean by this

I mean the settings of the "Open and share" module (my apologies I didn't realize I used the internal name of the module) like custom tabs, incognito, etc. I can guess some of these by looking at the second screenshot, in fact I can see the one I was concerned about (custom tabs), but just in case, while we are at it, could you share said config?

> 5. I think there is a unintended word mistake in this. The issue happens when I send the clean/ processed link **from** URLCheck **to** the browser. The very last step and task of the app, so to speak.

Whoops, I changed the message before sending and it looks like I made a total mess. Let me write that again.
You state this happens when sharing to URLCheck and then you "Open with" Brave/Cromite/Free browser. If instead of sending the URL to URLCheck via sharing you do it via opening (you need to have URLCheck as default browser), does the issue keep happening?

Thank you.

**Comment by TrianguloY** [comment]
My main question is: What do you mean by `browser opens link in minimized tab and stops loading it further` ?

If you could provide a video that would be perfect, but don't worry if not.

**Comment by TrianguloY** [comment]
> I just managed to catch the issue: 
> 
> I hope you can spot the fingertips. As one should recognise, tipping on the minimised tab won't enlarge it, as it should- it remains unresponsive.
> When I close the browser and repeat the steps for a second time, everything will most likely work.
> Frustratingly, this repetition won't fix anything for long, if at all.

That's very helpful, thanks! 
But it's very strange...the fact that you cannot interact with it...it's something with the browser, only triggered by my app? Huh...

**Comment by pokegamer5547** [comment]
> @TrianguloY That's what I thought at first. But the fact, that this issue happens with any other browser as well, confused me. It **may** still be a browser-side issue in the end, though.

Not trying to promote other apps but there's an app called "link eye" on fdroid which supports opening links as default browser to list all browsers or share to it to get list just like urlchecker. Can you test this bug using that? It may help figuring out whether this is specifically this urlchecker bug or how android browsers behave in general.

**Comment by pokegamer5547** [comment]
> @pokegamer5547 I tested it with "link-eye" as standard browser, "open with"-command and around 30 links, there hasn't been an error once.

Oh i see, what about sharing links to it?
