### ISSUE TITLE
unshort: link contains URL=

### ISSUE THREAD

**Issue by pokegamer5547** [TrianguloY/UrlChecker#357]
### Steps to reproduce

1. Open this [link](https://brodierobertson.xyz/amazonusa)  via urlcheck.
2. Click unshort button

### Expected behavior

It should give exact url it's gonna redirect to.

### Actual behavior

It gives "URL=" before the actual url. 

### URLCheck version

2.15

### Android version

android 13

### Android Custom/Specific ROM or Device

lineage os 20

### Other details

Other links works fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
I'm afraid that's a bug with Unshorten.me itself. If you open their [main page](https://unshorten.me/) and paste the url there, you also get the URL= prefix. The [api](https://unshorten.me/json/https://brodierobertson.xyz/amazonusa) is returning it, and even tough the app could remove it, that would mean changing what the api is supposed to return.

I don't see any issue with the page itself (maybe the prefix should be lowercase, but I don't know).

If you use this url a lot, you can create a pattern to remove it automatically for you.
Alternatively you can try to contact unshorten.me too see if they can fix that url.

I'm going to close this issue, since it's not an issue with the app, but with an external service.

**Comment by pokegamer5547** [comment]
> I'm afraid that's a bug with Unshorten.me itself. If you open their [main page](https://unshorten.me/) and paste the url there, you also get the URL= prefix. The [api](https://unshorten.me/json/https://brodierobertson.xyz/amazonusa) is returning it, and even tough the app could remove it, that would mean changing what the api is supposed to return.
> 
> I don't see any issue with the page itself (maybe the prefix should be lowercase, but I don't know).
> 
> If you use this url a lot, you can create a pattern to remove it automatically for you. Alternatively you can try to contact unshorten.me too see if they can fix that url.
> 
> I'm going to close this issue, since it's not an issue with the app, but with an external service.

Ah i see, you seems right it seems either a app on unshort server side, or a character errors or smt of the link. I'm sorry I should have tested more.
