### ISSUE TITLE
URL encoding problem with the `Uri Parts` module

### ISSUE THREAD

**Issue by CloneWith** [TrianguloY/UrlChecker#358]
### Steps to reproduce

1. Use a URL with `%25` inside. I used `https://example.com?prefill_%25E6%259D%25A5%25E6%25BA%2590=%E5%B8%AE%E5%8A%A9%E4%B8%8E%E5%8F%8D%E9%A6%88&hide=true`.
2. In the `Parameters` section, remove the `hide` parameter.

### Expected behavior

1. Expected parameter: `prefill_来源` -> `帮助与反馈`
2. Expected URL: `https://example.com?prefill_%E6%9D%A5%E6%BA%90=%E5%B8%AE%E5%8A%A9%E4%B8%8E%E5%8F%8D%E9%A6%88`

### Actual behavior

1. Before removing the parameter, saw: `prefill_æ¥æº` -> `帮助与反馈`
2. Actual URL: `https://example.com?prefill_%C3%A6%C2%9D%C2%A5%C3%A6%C2%BA%C2%90=%E5%B8%AE%E5%8A%A9%E4%B8%8E%EF%BF%BD%C2%8D%E9%A6%88`
3. The URL was broken, just displaying the *actual parameter* shown above.

### URLCheck version

2.15

### Android version

Android 13

### Android Custom/Specific ROM or Device

MIUI 14.0.10

### Other details

I think the module / application didn't handle symbol `%` (i.e. `%25` in URLs) properly. Or does it directly use the parameter from the module?

This case only appears in links with non-ASCII characters and `%25`s. What a strange issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
Ok, so I finally had time to look into this.

The issue is precisely that, due to how the module performs the decode, it is being decoded twice.

A url like `https://example.com?prefill_%2525=%2525` is invalid, or rather is encoded twice.

If you use any online decoder (or a browser developer console) you'll see that the decoded query for that url is `%25` = `%25`, and not `%` = `%` (because that would require decoding twice, which should not happen).

As I said, due to how I'm parsing the url the decoding was effectively being performed twice, but (and this is the funny part) the official android query parser is fundamentally broken and doesn't decode properly non-ascii characters. Currently it works because the first decode step is done by the url parser, but failed on that url due to the decoding twice.

Anyway, what I did is to avoid decoding the percentage in that second step. The final url will not be your expected behavior, because the %25 will still be kept (and displayed) but as I said that should be the "correct" thing to do, and it will also avoid the current invalid chars.
